#!/bin/sh
set -e

cd "$(dirname "$0")"

for package in chef ruby1.9.1 ruby1.9.1-dev build-essential; do
    if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
        # add a space after old values
        missing="${missing:+$missing }$package"
    fi
done
if [ -n "$missing" ]; then
    echo "$0: installing missing required packages: $missing" 1>&2
    sudo \
	env DEBIAN_FRONTEND=noninteractive DEBIAN_PRIORITY=critical \
	apt-get \
	-q \
        -o Dpkg::Options::=--force-confnew \
        install \
        --no-install-recommends \
        --assume-yes \
	-- \
	$missing
fi


sudo chef-solo -c solo.rb -j solo.json
